apiVersion: apps/v1

# Type of resource
kind: Deployment

# Information use for query
metadata:
  name: hello-kiamol-4

# Details spec of resource
spec:
  # For other resource to select
  selector:
    matchLabels:
      app: hello-kiamol-4
  template:
    # Use for query Pod because under the hood, Deployment manage Pods
    metadata:
      labels:
        app: hello-kiamol-4
    spec:
      containers:
      - name: web
        image: kiamol/ch02-hello-kiamol